[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.build]
disabled = true

[tasks.test]
disabled = true

[tasks.app-css]
script_runner = "@shell"
script= '''
npx @tailwindcss/cli -i ./maes/tailwind.css -o ./maes/assets/tailwind.css
'''

[tasks.app-css-watch]
script_runner = "@shell"
script= '''
npx @tailwindcss/cli -i ./maes/tailwind.css -o ./maes/assets/tailwind.css --watch
'''

[tasks.client-css]
script_runner = "@shell"
script= '''
npx @tailwindcss/cli -i ./client/tailwind.css -o ./client/assets/tailwind.css
'''

[tasks.client-css-watch]
script_runner = "@shell"
script= '''
npx @tailwindcss/cli -i ./client/tailwind.css -o ./client/assets/tailwind.css --watch
'''

[tasks.app-dev]
dependencies = ["app-css"]
script_runner = "@shell"
script= '''
dx serve --package maes --platform desktop --watch false --hot-reload false
'''

[tasks.app-dev-watch]
dependencies = ["app-css"]
script_runner = "@shell"
script= '''
dx serve --package maes --platform desktop
'''

[tasks.app-bundle]
dependencies = ["app-css"]
script_runner = "@shell"
script= '''
dx bundle --release --package maes --platform desktop
'''

[tasks.client-dev]
dependencies = ["client-css"]
script_runner = "@shell"
script= '''
dx bundle --release --package client --platform web --target wasm32-unknown-unknown
xcopy /S /Y /I "target/dx/client/release/web/public" "%AppData%/maes/client"
'''

[tasks.client]
dependencies = ["client-css"]
script_runner = "@shell"
script= '''
dx bundle --release --package client --platform web --target wasm32-unknown-unknown
'''