[package]
name = "server-lib"
edition.workspace = true
version.workspace = true
description.workspace = true
keywords.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
core-lib = { path = "../core", features = ["server"] }
tokio = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
tower-http = { workspace = true }
surrealdb = { workspace = true }
serde = { workspace = true }

[build-dependencies]
dotenvy = { workspace = true }